### PR TITLE
Fields of type"typing.Annotated" are not supported in pydantic

### PR DESCRIPTION
**Pull request by kashyab12**
#490 

Reproduced the issue with `pydantic==1.7.4`. After looking at the `pydantic` [changelog](https://docs.pydantic.dev/latest/changelog/#v18-2021-02-26) `v1.8 2021-02-26` introduced support for `typing.Annotated` hints on model fields. After installing `pydantic==1.8` and trying to reproduce the issue, no errors were produced.

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Thanks! In the github yaml files, the pydantic version is hardcoded for the unit tests, can you set it to 1.8.0 instead of just 1.* so that our unit tests run with the oldest version possible? Thanks!

**Comment by kashyab12** [comment]
> Thanks! In the github yaml files, the pydantic version is hardcoded for the unit tests, can you set it to 1.8.0 instead of just 1.* so that our unit tests run with the oldest version possible? Thanks!

@gabrieldemarmiesse after modifying the `pydantic` version in the github jobs, lots of tests are failing. Upon taking a look at the stacktrace seems like the `pydantic` object is missing the `__version__` attribute. [This issue](https://github.com/pydantic/pydantic/issues/2572) was fixed in [version 1.9 according to the changelog](https://docs.pydantic.dev/latest/changelog/#v190a1-2021-12-18-changes). So either:
- We modify the job to use version 1.9 (not the oldest version), which wouldn't tell us whether a new change breaks compatability with version 1.8; or
- Modify both minimum supported version and job version to use 1.9; or
- Modify references to `__version__` and obtain the version by some other means.

**Comment by gabrieldemarmiesse** [comment]
We can se the minimul version to 1.9. That why we have our CI!

**Comment by kashyab12** [comment]
@gabrieldemarmiesse I've updated CI to use `pydantic==1.9`.

**Review by gabrieldemarmiesse — APPROVED** [review]

**Comment by gabrieldemarmiesse** [comment]
Many thanks!

**Pull request merged**
