### PR TITLE
add --project-directory flag to compose

### PR DESCRIPTION
**Pull request by John-Vash**
Add support for env_file's that are not in the same directory as the compose file.

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Awesome! Thank you for the pull request!

**Review by gabrieldemarmiesse — APPROVED** [review]
Very nice of you to add the unit tests :)

**Comment by gabrieldemarmiesse** [comment]
We have several linters that we use for this project. Among them are isort, black and flake8. Could you run them and push again?

Something along the lines of 
```
isort ./ && black ./ && flake8
```
should be enough

**Comment by John-Vash** [comment]
sorry about that, fixes have been pushed.

**Pull request merged**
