### PR TITLE
`return_stderr` should be True for `run` method to return tuple

### PR DESCRIPTION
**Pull request by rafrafek**
I think it's intended to work that way

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Maybe there is a misunderstanding? When using overloads, the things that are used in the signature are the types, not the default values. I think the default value is not used here by type checkers, only the default value of the original signature counts

**Comment by rafrafek** [comment]
For me Pylance complains when `return_stderr: Literal[True] = False`:
```
Expression of type "Literal[False]" cannot be assigned to parameter of type "Literal[True]"
  "Literal[False]" cannot be assigned to type "Literal[True]"
```

It makes sense for me to not assign `Literal[False]` to `Literal[True]` 😅

> When using overloads, the things that are used in the signature are the types, not the default values.

I've pushed commit that replaces default values with `...` to address this.

**Comment by rafrafek** [comment]
There is `input: bytes = None` in `run()`, shouldn't it be `input: Optional[bytes] = None`?

https://stackoverflow.com/a/49724148/9737275

That's what I've found:

> Type checkers should move towards requiring the optional type to be made explicit.

**Comment by gabrieldemarmiesse** [comment]
I agree that if the default value is None, then it should be optional. I'll take a look at the docs for the overloads

**Review by gabrieldemarmiesse — APPROVED** [review]
Thank you for the pull request!

**Comment by gabrieldemarmiesse** [comment]
> There is input: bytes = None in run(), shouldn't it be input: Optional[bytes] = None?

That is indeed the case. Can you open a new pull request for this fix?

**Comment by rafrafek** [comment]
> That is indeed the case. Can you open a new pull request for this fix?

Done! :)

**Pull request merged**
