### PR TITLE
Add volumes option to docker.compose.run() (#662)

### PR DESCRIPTION
**Pull request by www84**
Implemented option for --volume in docker.compose.run() including tests.

### CODE REVIEW

**Comment by www84** [comment]
Okay, my IDE told me on commit that test_compose.py has Windows line breaks, but I thought that I accidentally switched this one file to Windows line breaks it in my IDE, so I changed it to Linux line breaks. Let me quickly fix that back to Windows line breaks.

**Comment by www84** [comment]
It's back to Windows line breaks. The question is, thought, if this is desired or if this is an oversight and all files should have Linux line breaks.

**Review by gabrieldemarmiesse — APPROVED** [review]
Very nice pull request! Thanks!

**Comment by gabrieldemarmiesse** [comment]
> It's back to Windows line breaks. The question is, thought, if this is desired or if this is an oversight and all files should have Linux line breaks.

Linux line breaks are preferred but I don't want to have to check it at every pull request so I don't ask people to change it if I notice it. A github action checking that all line breaks are linux style would be the best, as it would give quick feedback to contributors but it's not a big deal if we don't have it.

**Comment by www84** [comment]
> Linux line breaks are preferred but I don't want to have to check it at every pull request so I don't ask people to change it if I notice it. A github action checking that all line breaks are linux style would be the best, as it would give quick feedback to contributors but it's not a big deal if we don't have it.
Alright. I agree that it's not a big issue. One last PR coming up in a few minutes. Thank you for reviewing at this time of the year. :+1:

**Pull request merged**
