### PR TITLE
Allow the streaming of the docker.compose.pull logs

### PR DESCRIPTION
**Pull request by HemaZ**
same as #496 but for compose.pull. The test will most probably fail but i couldn't run it locally. having some problem with the docker registry, so hopefully it will run on github action and i will update it to the expected output

### CODE REVIEW

**Comment by HemaZ** [comment]
oh so it seems the docker hub issue is a problem with docker hub itself.

**Comment by gabrieldemarmiesse** [comment]
Indeed I had the same issue. Dockerhub seems to be having a bad time

**Comment by HemaZ** [comment]
> Indeed I had the same issue. Dockerhub seems to be having a bad time

I think it got fixed. This passes now

**Review by gabrieldemarmiesse — APPROVED** [review]
Many thanks for the pull request! You're the 50th contributor of Python-on-whales! Sadly I don't have any prize, but you can be proud to add another cool feature to the lib that many users will appreciate!

**Comment by HemaZ** [comment]
> Many thanks for the pull request! You're the 50th contributor of Python-on-whales! Sadly I don't have any prize, but you can be proud to add another cool feature to the lib that many users will appreciate!

Thank you for creating this amazing project. It saved me a lot of time and i really appreciate it.

**Comment by gabrieldemarmiesse** [comment]
I'm happy to hear it! The nice words of people like you are a good reason for me to work in this library :)

**Pull request merged**
