### PR TITLE
docker compose ls -> docker.compose.ls()

### PR DESCRIPTION
**Pull request by marshall7m**
Fixes issue #367 

Implements docker.compose.ls() method that wraps around `docker compose ls` command

I'd be more than happy to make any styling changes and add any additional tests

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Sorry for the delay of the review, I'm currenly moving, so I might now have to time this week to look at it :(

**Comment by marshall7m** [comment]
> Sorry for the delay of the review, I'm currenly moving, so I might now have the time this week to look at it :(

No worries, thanks for the update. When you do get a chance if you can help me figure out why the `ConfigFiles` key is not available from the `json.loads(run(full_cmd))` output. Strangely, it's available when I run it locally but not within the GH actions job which causes the test to fail on the `ConfigFiles` assertion. It's definitely not a race condition in terms of the project not being available in time for the `docker compose ls` command given the `json.loads(run(full_cmd))` output contains: `[{'Name': 'test_compose_ls', 'Status': 'running(1)'}]` (see [gh job](https://github.com/gabrieldemarmiesse/python-on-whales/actions/runs/3147294506/jobs/5116661874))

**Comment by gabrieldemarmiesse** [comment]
docker compose is in constant evolution. I wouldn't be surprised if you don't have the same version of compose locally and in the CI (the CI probably has an older version). Thus depending on the version we shouldn't assume that the ConfigFiles key will always be present. 

If you still want to test it, and make sure the test works on any platform, you can try to feed your function a json string that was copy-pasted from the output of `docker compose ls` on your computer

Also, can you try to avoid using regex? It's difficult for new contributors to understand the type of parsing that is being done. Using `.split()` should be enough in this situation :)

**Review by gabrieldemarmiesse — CHANGES_REQUESTED** [review]
Very cool pull request, just some small changes and we can merge :)

**Review by gabrieldemarmiesse — APPROVED** [review]

**Pull request merged**
