### PR TITLE
Additional Docker Compose Run Flags

### PR DESCRIPTION
**Pull request by ethanleifer**
First time pring here. 

Fixing Issue #442 

I added two flags to `compose.run`

```python
build: bool = False
```
I added them using the `full_cmd.add_flag` function. 

I matched the default values and ordering of the [docker compose docs](https://docs.docker.com/engine/reference/commandline/compose_run/#options)

### CODE REVIEW

**Review by gabrieldemarmiesse — CHANGES_REQUESTED** [review]
Thank you for the pull request. Could you write some simple unit tests for those two flags? Thanks a lot. You can write them here: https://github.com/gabrieldemarmiesse/python-on-whales/blob/master/tests/python_on_whales/components/test_compose.py

You can read the other tests for inspiration.

**Comment by ethanleifer** [comment]
I removed the remove_orphans since I was having issues getting the expected output locally

**Comment by gabrieldemarmiesse** [comment]
Thank you! I'll take a look :)

**Review by gabrieldemarmiesse — APPROVED** [review]

**Comment by gabrieldemarmiesse** [comment]
Thank you for the pull request!

**Pull request merged**
