### PR TITLE
Enable labeling networks in network create

### PR DESCRIPTION
**Pull request by Akshay04**
Add missing functionality to docker network create function to add labels to network

### CODE REVIEW

**Comment by tot0** [comment]
Awesome thanks!

**Comment by gabrieldemarmiesse** [comment]
That's great! Thanks a lot! Could you add a small unit test? :)

**Comment by Akshay04** [comment]
Added the unit test, I was having some trouble testing my changes locally. How do you typically do this?

**Comment by gabrieldemarmiesse** [comment]
You need to install the linters and formatters:
Isort, black and flake 8. Run the at the root of the repo to check things.

Next to run the tests, install this package in editable mode `pip install -e . ` from the root of the repo too.

Install the test requirements too
`pip install -r tests/requirements.txt`

Then run a test with
`pytest path/to/file.py::function_to_run`.

The test looks good. Could you just create the network with a context manager so that it's deleted afterwards even if there are exceptions?
`with docker.network.create(...) as my_network:`

**Comment by Akshay04** [comment]
Will do, thanks for your help

**Review by gabrieldemarmiesse — APPROVED** [review]

**Pull request merged**
