### PR TITLE
Remove download docker client functionality

### PR DESCRIPTION
**Pull request by LewisGaul**
Removes dependency on typer/tqdm/requests by dropping support for downloading the docker client.

Initially agreed at https://github.com/gabrieldemarmiesse/python-on-whales/issues/512#issuecomment-1872322431, this has been deprecated since https://github.com/gabrieldemarmiesse/python-on-whales/pull/577 (v0.71.0 released in April 2024), and agreed we can now remove at https://github.com/gabrieldemarmiesse/python-on-whales/issues/552#issuecomment-2331356820. If accepted, this supercedes https://github.com/gabrieldemarmiesse/python-on-whales/pull/513 as a resolution to https://github.com/gabrieldemarmiesse/python-on-whales/issues/512. We will also be able to close https://github.com/gabrieldemarmiesse/python-on-whales/issues/575.

### CODE REVIEW

**Comment by LewisGaul** [comment]
@gabrieldemarmiesse are we ready to merge this do you think?

**Review by gabrieldemarmiesse — APPROVED** [review]
I'm deeply sorry for the late reply there. Thanks for the PR and the description. I believe we should have a section of the docs dedicated to installing the docker cli without the engine since people whose code won't work anymore will look for a solution and might not be aware that they need an apt-get or similar to replace the "download-cli". If you wish, that can be in another PR, but we should write that up before making a release.

**Comment by LewisGaul** [comment]
Can we just link to https://docs.docker.com/engine/install/ and https://podman.io/docs/installation? Where in the docs were you thinking this should go?

**Comment by gabrieldemarmiesse** [comment]
We should definitely link those.
I think the instructions should go to https://gabrieldemarmiesse.github.io/python-on-whales/docker_client/

I'm not sure linking is enough, we should additionally tell users that they don't need the engine and containerd and don't need to use systemd or systemctl to create the docker service.

The docker docs are not great if you just want to install the client so we should fill this gap. We just need to tell users what steps are not needed.

**Review by gabrieldemarmiesse — APPROVED** [review]
This looks really good, thanks! We'll pin an issue and display it loudly in the release notes, that should help with visibility. Thanks for everything!

**Comment by LewisGaul** [comment]
Oh, there are some doc updates I was still working on sorry, I'll have to raise in a separate PR

**Comment by gabrieldemarmiesse** [comment]
Something fancy could also be to re-enable CLI entrypoint (without typer) just to print the message that CLI isn't supported by python-on-whales anymore, so that people using it don't just get the "command not found" error. But that's slightly more work. What do you think?

**Comment by LewisGaul** [comment]
Hm could do, unsure how many users would actually be relying on it...

Here's the follow-up PR: https://github.com/gabrieldemarmiesse/python-on-whales/pull/639

**Pull request merged**
